### PR TITLE
[#250] Fix: Comment is not cleared after sending successfully and keyboard got dismissed when sending

### LINKED ISSUE #250: Fix: Comment is not cleared after sending successfully and keyboard got dismissed when sending
## Issue

Comment is not cleared after sending successfully and the text box's keyboard is automatically dismissed for a brief duration during the comment sending process.

https://user-images.githubusercontent.com/70877098/142130184-e4e4aec8-d6a8-4f7b-b946-8796e5bd8efe.MP4

## Expected

Comment should be cleared after sending successfully and the text box's keyboard should not be dismissed during the sending process.

## Steps to reproduce

1. Logged in the app with valid credentials
2. Open an article
3. Go to comments section
4. Send a comment
5. Observe the result

### PR DESCRIPTION
**Pull request by markgravity**
Resolved #250 

## What happened

- Refactor `AppTextView`
- Clear comment input when posting successfully
- Tap outside to dismiss keyboard when comment input is focused

## Insight

n/a

## Proof Of Work

https://user-images.githubusercontent.com/17875522/142378614-aa1fac04-465f-4c8b-a6de-61869b180e72.mov

### CODE REVIEW

**Comment by minhnimble** [comment]
@markgravity wait I saw in the PoW user has to select the text and delete manually. Is that correct?

**Review by minhnimble — CHANGES_REQUESTED** [review]
There is no cursor when typing in the textview ... going back to the old issue when refactor to use View for TextView that I told you... please help check again @markgravity 


https://user-images.githubusercontent.com/70877098/142373936-f7f32de2-d7d1-4dc0-8ecc-04793afeb437.MP4

**Comment by minhnimble** [comment]
Please add some bottom paddings for the comment textbox

**Comment by minhnimble** [comment]
@markgravity the textView now has inconsistent behavior with other textFields that when focusing the placeholder text doesn't disappear, which looks a bit weird to me.

**Review by minhnimble — APPROVED** [review]
LGTM 🚀

**Review by suho — APPROVED** [review]

**Pull request merged**
