### PR TITLE
[#1] [Chore] Setup project - Part 2

### LINKED ISSUE #1: Set up project repository
## Why

When starting a new project, the project repository foundations need to be in placed for smooth application's development with proper app building and running tests guidance.

## Acceptance Criteria
- [ ] Add pull request and issue templates.
- [ ] Setup proper `.gitignore` file for the project.
- [ ] Setup all necessary 3rd party libraries such as: RxSwift, Alamofire, etc. and library management tools such as: CocoaPods, Swift Package Manager, etc.
- [ ] Run the script from iOS template to generate initial classes and folder structure or create manually.
- [ ] Setup `README.md` file with proper description, setup/testing instruction, features requirements and API specs links.

### PR DESCRIPTION
**Pull request by markgravity**
Resolved #1 

## What happened

When starting a new project, the project repository foundations need to be in place for smooth application development with proper app building and running tests guidance.

## Insight

- Create xcode project and folder structure
- Add staging & production schema
 
## Proof Of Work

Screen Shot 2021-08-06 at 09 33 35

### CODE REVIEW

**Review by minhnimble — APPROVED** [review]
Nice work, LGTM 🚀

**Comment by suho** [comment]
@markgravity Please check again this, you should merge `chore/1-setup-project-part-2` into `develop` instead of `chore/1-setup-project`. Please reverse the commit

**Comment by suho** [comment]
also, please rebase the branch `chore/1-setup-project-part-2` first, before merging.

**Comment by markgravity** [comment]
> @markgravity Please check again this, you should merge `chore/1-setup-project-part-2` into `develop` instead of `chore/1-setup-project`. Please reverse the commit

Oops, It usually changes to `develop` automatically when I merge `chore/1-setup-project` into `develop`. 
Let's me update it manually 😢

**Pull request merged**
